/*
 * One executable per platform: the API, the staff app and the migrations inside.
 *
 *   bun dev/build-box.ts                 → this machine
 *   bun dev/build-box.ts bun-windows-x64 → cross-compile (also bun-linux-x64, bun-linux-arm64,
 *                                          bun-darwin-x64, bun-darwin-arm64)
 */
import { readdirSync, statSync, mkdirSync } from "node:fs";
import { join, relative, sep } from "node:path";

const root = join(import.meta.dir, "..");
const target = process.argv[2] ?? "";
const dist = join(root, "apps/captain-pwa/dist");
const drizzleDir = join(root, "packages/db/drizzle");

// 1. The staff app, built for the Box (no diner origin — QR is hidden offline anyway;
// ODR_OFFLINE flips the inlined config to {offline:true}, see build-web.ts).
const web = Bun.spawnSync(["bun", "dev/build-web.ts", "captain-pwa"], { cwd: root, env: { ...process.env, DINER_ORIGIN: "", ODR_OFFLINE: "1" }, stdout: "inherit", stderr: "inherit" });
if (web.exitCode !== 0) process.exit(web.exitCode);

// 2. One `with { type: "file" }` import per built file, so `bun build --compile` embeds them.
// Sorted so the generated file is byte-identical across runs with no source changes.
const walk = (dir: string): string[] =>
  readdirSync(dir)
    .sort()
    .flatMap((n) => {
      const p = join(dir, n);
      return statSync(p).isDirectory() ? walk(p) : [p];
    });
const lines = ["// GENERATED by dev/build-box.ts — do not edit. Maps URL path → embedded file path."];

const files = walk(dist)
  .map((f) => relative(dist, f).split(sep).join("/"))
  .filter((rel) => !rel.startsWith("docs/")); // the /docs pages are cloud-only
const entries: string[] = [];
files.forEach((rel, i) => {
  lines.push(`import a${i} from ${JSON.stringify("../../captain-pwa/dist/" + rel)} with { type: "file" };`);
  // ponytail: .html/.json files are real TS-resolvable modules (HTMLBundle / parsed JSON) even
  // under `type: "file"`, so cast to the string path `with { type: "file" }` actually gives at runtime.
  entries.push(`  ${JSON.stringify("/" + rel)}: a${i} as unknown as string,`);
});
lines.push("export const assets: Record<string, string> = {", ...entries, "};");

// 3. Migrations travel inside the binary too: import each .sql and the journal as files,
//    and point ODR_MIGRATIONS at their embedded folder at runtime (see serve.ts).
const migFiles = walk(drizzleDir)
  .map((f) => relative(drizzleDir, f).split(sep).join("/"))
  .filter((rel) => !rel.includes("_snapshot.json"));
const migEntries: string[] = [];
migFiles.forEach((rel, i) => {
  lines.push(`import m${i} from ${JSON.stringify("../../../packages/db/drizzle/" + rel)} with { type: "file" };`);
  migEntries.push(`  ${JSON.stringify(rel)}: m${i} as unknown as string,`);
});
lines.push("export const migrations: Record<string, string> = {", ...migEntries, "};");

await Bun.write(join(root, "apps/box/src/assets.gen.ts"), lines.join("\n") + "\n");

// 4. Compile.
mkdirSync(join(root, "apps/box/dist"), { recursive: true });
const ext = target.includes("windows") ? ".exe" : "";
const out = join(root, `apps/box/dist/odr-box-${target || "host"}${ext}`);
const args = ["bun", "build", "--compile", "--minify", ...(target ? [`--target=${target}`] : []), "apps/box/src/main.ts", "--outfile", out];
// ponytail: Bun only accepts --windows-hide-console when compiling *on* Windows itself,
// even for a cross-compiled Windows target — so only add it there.
if (target.includes("windows") && process.platform === "win32") args.push("--windows-hide-console");
const build = Bun.spawnSync(args, { cwd: root, stdout: "inherit", stderr: "inherit" });
if (build.exitCode !== 0) process.exit(build.exitCode);
console.log(`▸ ${relative(root, out)} (${(statSync(out).size / 1e6).toFixed(1)} MB)`);
