// GENERATED by dev/build-box.ts — do not edit. URL path → embedded file path; migration file → embedded path.
export const assets: Record<string, string> = {};
export const migrations: Record<string, string> = {};
