// GENERATED by dev/build-box.ts — do not edit. Maps URL path → embedded file path.
import a0 from "../../captain-pwa/dist/chunk-kpt0m0z1.css" with { type: "file" };
import a1 from "../../captain-pwa/dist/chunk-qnb2r1rk.js" with { type: "file" };
import a2 from "../../captain-pwa/dist/config.json" with { type: "file" };
import a3 from "../../captain-pwa/dist/icon.png" with { type: "file" };
import a4 from "../../captain-pwa/dist/index.html" with { type: "file" };
import a5 from "../../captain-pwa/dist/manifest.webmanifest" with { type: "file" };
import a6 from "../../captain-pwa/dist/mark.svg" with { type: "file" };
export const assets: Record<string, string> = {
  "/chunk-kpt0m0z1.css": a0 as unknown as string,
  "/chunk-qnb2r1rk.js": a1 as unknown as string,
  "/config.json": a2 as unknown as string,
  "/icon.png": a3 as unknown as string,
  "/index.html": a4 as unknown as string,
  "/manifest.webmanifest": a5 as unknown as string,
  "/mark.svg": a6 as unknown as string,
};
import m0 from "../../../packages/db/drizzle/0000_brown_korath.sql" with { type: "file" };
import m1 from "../../../packages/db/drizzle/0001_lazy_marvel_boy.sql" with { type: "file" };
import m2 from "../../../packages/db/drizzle/0002_sticky_human_torch.sql" with { type: "file" };
import m3 from "../../../packages/db/drizzle/0003_sleepy_agent_brand.sql" with { type: "file" };
import m4 from "../../../packages/db/drizzle/0004_red_manta.sql" with { type: "file" };
import m5 from "../../../packages/db/drizzle/0005_abnormal_magdalene.sql" with { type: "file" };
import m6 from "../../../packages/db/drizzle/0006_tranquil_switch.sql" with { type: "file" };
import m7 from "../../../packages/db/drizzle/0007_worthless_mephisto.sql" with { type: "file" };
import m8 from "../../../packages/db/drizzle/0008_spicy_doorman.sql" with { type: "file" };
import m9 from "../../../packages/db/drizzle/0009_productive_masque.sql" with { type: "file" };
import m10 from "../../../packages/db/drizzle/0010_faithful_black_bird.sql" with { type: "file" };
import m11 from "../../../packages/db/drizzle/0011_wakeful_blindfold.sql" with { type: "file" };
import m12 from "../../../packages/db/drizzle/meta/_journal.json" with { type: "file" };
export const migrations: Record<string, string> = {
  "0000_brown_korath.sql": m0 as unknown as string,
  "0001_lazy_marvel_boy.sql": m1 as unknown as string,
  "0002_sticky_human_torch.sql": m2 as unknown as string,
  "0003_sleepy_agent_brand.sql": m3 as unknown as string,
  "0004_red_manta.sql": m4 as unknown as string,
  "0005_abnormal_magdalene.sql": m5 as unknown as string,
  "0006_tranquil_switch.sql": m6 as unknown as string,
  "0007_worthless_mephisto.sql": m7 as unknown as string,
  "0008_spicy_doorman.sql": m8 as unknown as string,
  "0009_productive_masque.sql": m9 as unknown as string,
  "0010_faithful_black_bird.sql": m10 as unknown as string,
  "0011_wakeful_blindfold.sql": m11 as unknown as string,
  "meta/_journal.json": m12 as unknown as string,
};
